services:
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: vcmi-portal
    # ports:
    #   - "8000:8000" (nginx, see the container below) uncomment this if you just want to run this locally and expose the portal service to :8000
    restart: unless-stopped
    networks:
      - vcmi-longplay
    env_file:
      - env.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "1"

  host:
    build:
      context: ..
      dockerfile: longplay/host/Dockerfile
    container_name: vcmi-host
    # ports: # enable only for debugging purposes, otherwise desktop access from portal-proxy can be bypassed
    #   - "3000:3000"
    #   - "3001:3001"
    volumes:
      - host-data:/home/abc/.local/share/vcmi
    depends_on:
      - portal
    restart: unless-stopped
    shm_size: "1gb"
    networks:
      - vcmi-longplay
    environment:
      - SELKIES_FRAMERATE=15-30
      - SELKIES_H264_CRF=30-50
      - SELKIES_JPEG_QUALITY=40
      - SELKIES_MANUAL_WIDTH=1920
      - SELKIES_MANUAL_HEIGHT=1080
      - SELKIES_AUDIO_BITRATE=128000
      - SELKIES_MICROPHONE_ENABLED=False
      - SELKIES_FILE_TRANSFERS="none"
      - SELKIES_SECOND_SCREEN=False
      - SELKIES_ENABLE_SHARING=False
      - SELKIES_ENABLE_AUTH=False
    env_file:
      - env.conf
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "1"

  nginx: # in order to host over the internet, we need https certs, to do so, configure https/tls with certbot or something, and proxy https -> http using nginx, otherwise you can just comment this whole service
      image: nginx:latest
      container_name: vcmi-nginx
      ports:
        - "8086:80"
        - "8087:443"
      env_file:
        - env.conf
      volumes:
        # Mount the template here instead of mounting nginx.conf directly
        - ./templates:/etc/nginx/templates:ro
        - /etc/letsencrypt:/etc/letsencrypt:ro
      restart: unless-stopped
      networks:
        - vcmi-longplay
      depends_on:
        - portal
      logging:
        driver: json-file
        options:
          max-size: "30m"
          max-file: "1"

volumes:
  host-data:

networks:
  vcmi-longplay:
    driver: bridge