services:
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: vcmi-portal
    ports:
      - "8000:8000"
    volumes:
      - saves-data:/saves
    environment:
      - SAVES_DIR=/saves
    restart: unless-stopped
    networks:
      - vcmi-longplay
    env_file:
      - env.conf

  host:
    build:
      context: ..
      dockerfile: longplay/host/Dockerfile
    container_name: vcmi-host
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - host-data:/home/abc/.local/share/vcmi
    depends_on:
      - portal
    restart: unless-stopped
    shm_size: "1gb"
    networks:
      - vcmi-longplay
    environment:
      - SELKIES_FRAMERATE=15-30
      - SELKIES_H264_CRF=30-50
      - SELKIES_JPEG_QUALITY=40
      - SELKIES_MANUAL_WIDTH=1280
      - SELKIES_MANUAL_HEIGHT=720
      - SELKIES_AUDIO_BITRATE=128000
      - SELKIES_MICROPHONE_ENABLED=False
      - SELKIES_FILE_TRANSFERS="none"
      - SELKIES_SECOND_SCREEN=False
      - SELKIES_ENABLE_SHARING=False
    env_file:
      - env.conf

volumes:
  saves-data:
  host-data:

networks:
  vcmi-longplay:
    driver: bridge